# Generated by Django 4.1.7 on 2024-03-04 15:35

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blog_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50),
        ),
    ]
