# Generated by Django 4.1.7 on 2024-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Ange Font Awesome ikonklassen (t.ex. 'fas fa-user').", max_length=100),
        ),
    ]
